### ISSUE TITLE
Where can I find the generated png images?

### ISSUE THREAD

**Issue by Ahmed-Sadek** [msfasha/Arabic-Deep-Learning-OCR#2]

**Comment by msfasha** [comment]
More details can be found at the repository home page:
https://github.com/msfasha/Arabic-Deep-Learning-OCR

The datasets can be found at:
https://drive.google.com/drive/u/0/mobile/folders/1mRefmN4Yzy60Uh7z3B6cllyyOXaxQrgg?usp=sharing

Most dataset files are in binary repository format where each binary file contains a collection of png images.Nevertness, one of the folders contains files in pages format.

**Comment by msfasha** [comment]
a utility program to extract png files from binary repository was recently included in the dataset Google drive as well as in this repository in GitHub.
Also, some usage guidelines were included in the notebook.
